version: "3.9"

services:
  api: &notify_orchestrator
    container_name: govuk_notify_orchestrator
    build: .
    ports:
      - "8026:8026"
    restart: "no"
    volumes:
      - ".:/notify_orchestrator"
    depends_on:
      rabbitmq:
        condition: "service_healthy"
        required: false

  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:3-management-alpine
    ports:
      - "5672:5672" # Advanced Message Queuing Protocol
      - "15672:15672" # Port for the management API
    volumes:
      - ./config/rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf
    healthcheck:
      test: ["CMD", "nc", "-z", "localhost", "5672"]
      interval: 5s
      timeout: 10s
      retries: 3
    profiles:
      # RabbitMQ will not run unless COMPOSE_PROFILES is set to 'development'
      - development

  celery_worker:
    <<: *notify_orchestrator
    container_name: celery_worker
    command:
      - "bin/run_worker.sh"
    ports: []
    environment:
      - CELERY_BROKER_URL=${CELERY_BROKER_URL:-amqp://guest:guest@rabbitmq:5672/}
    depends_on:
      rabbitmq:
        condition: "service_healthy"
        required: false
