name: "Deploy"
description: "Deploy docker image to namespace"
inputs:
    kube_cert:
        description: "Kubernetes cluster authentication certificate"
        required: true
    kube_token:
        description: "Kubernetes cluster authentication token"
        required: true
    kube_cluster:
        description: "Kubernetes cluster name"
        required: true
    kube_namespace:
        description: "Kubernetes cluster namespace"
        required: true
    app_environment:
        description: "environment to which the app is being deployed [staging, production, etc]"
        required: true
    ecr_registry_url:
        description: "ECR registry url"
        required: true
    ecr_image_tag:
        description: "ECR image tag"
        required: true

runs:
    using: "composite"
    steps:
    - name: Checkout
      uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd

    - name: Authenticate to the cluster
      uses: ministryofjustice/laa-reusable-github-actions/.github/actions/authenticate_to_cluster@2aa2676c3cd9876ec7037ee8b3d729d0306cb7c6
      with:
            kube-cert: ${{ inputs.kube_cert }}
            kube-token: ${{ inputs.kube_token }}
            kube-cluster: ${{ inputs.kube_cluster }}
            kube-namespace: ${{ inputs.kube_namespace }}

    - name: Deploy using Helm
      shell: bash
      run: ./bin/deploy.sh ${{ inputs.app_environment }}
      env:
        REGISTRY_HOST: ${{ inputs.ecr_registry_url }}
        IMAGE_TAG: ${{ inputs.ecr_image_tag }}
        ENVIRONMENT: ${{ inputs.app_environment }}
        NAMESPACE: ${{ inputs.kube_namespace }}