apiVersion: v1
kind: Service
metadata:
  name: {{ include "laa-govuk-notify-orchestrator.fullname" . }}-app
  labels:
    {{- include "laa-govuk-notify-orchestrator.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "laa-govuk-notify-orchestrator.selectorLabels" . | nindent 4 }}
