name: Workflow

on:
  pull_request:

permissions:
  contents: read

jobs:
# -------------------------------------------------- formatting and linting ---
  formatting-and-linting:
    name: "Formatting and linting"
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd
        - uses: ministryofjustice/laa-reusable-github-actions/.github/actions/python-linting-and-formatting@cb1ebcbca5efcd1e91b7ee1e27c73650c1bba9d8

# ------------------------------------------------------------ unit test ------
  unit-tests:
    name: "Unit tests"
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd
        - uses: ./.github/actions/unit-tests

# ------------------------------------------------------------ unit test ------
  integration-tests:
    name: "Integration tests"
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd
        - uses: ./.github/actions/integration-tests

# ---------------------------------------------------------- build (new) -----
  build:
    name: Build Docker Image
    runs-on: ubuntu-latest
    needs: [unit-tests, integration-tests, formatting-and-linting]
    outputs:
      image_tag: ${{ steps.branch-tag.outputs.tag }}
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd

      - name:  Set up AWS credentials
        uses: ministryofjustice/laa-reusable-github-actions/.github/actions/ecr-auth@cb1ebcbca5efcd1e91b7ee1e27c73650c1bba9d8
        with:
          ecr_region: ${{ vars.ECR_REGION }}
          ecr_role: ${{ secrets.ECR_ROLE_TO_ASSUME }}
          role-session-name: laa-govuk-notify-orchestrator

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@e468171a9de216ec08956ac3ada2f0791b6bd435
        with:
          install: true

      - name: Cache Docker layers
        uses: actions/cache@668228422ae6a00e4ad889ee87cd7109ec5666a7
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Set image tag
        id: branch-tag
        run: |
          if [ "${GITHUB_REF_NAME}" = "main" ]; then
            echo "tag=main-${GITHUB_SHA}" >> "$GITHUB_OUTPUT"
          else
            echo "tag=branch-${GITHUB_SHA}" >> "$GITHUB_OUTPUT"
          fi

      - name: Build and push image with caching
        uses: ministryofjustice/laa-reusable-github-actions/.github/actions/build_and_push_with_cache@main
        with:
         image_registry: ${{ secrets.ECR_REGISTRY_URL }}
         image_repo: ${{ vars.ECR_REPOSITORY }}
         dockerfile_path: Dockerfile
         image_tag: ${{  steps.branch-tag.outputs.tag  }}

# --------------------------------------------------------- development-production ---
  deploy-development:
    name: Deploy (development)
    runs-on: ubuntu-latest
    needs: build
    environment: development
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd

      - name: Deploy to development with composite action
        uses: ./.github/actions/deploy
        with:
          ecr_registry_url: ${{ secrets.ECR_REGISTRY_URL }}/${{ vars.ECR_REPOSITORY }}
          ecr_image_tag: ${{ needs.build.outputs.image_tag }}
          kube_cert:        ${{ secrets.KUBE_CERT }}
          kube_token:       ${{ secrets.KUBE_TOKEN }}
          kube_cluster:     ${{ secrets.KUBE_CLUSTER }}
          kube_namespace:   ${{ secrets.KUBE_NAMESPACE }}
          app_environment:  development

  # --------------------------------------------------------- staging-production ---
  deploy-staging:
    name: Deploy (staging)
    runs-on: ubuntu-latest
    needs: build
    environment: staging
    if: github.ref_name == 'main'
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd

      - name: Deploy to staging with composite action
        uses: ./.github/actions/deploy
        with:
          ecr_registry_url: ${{ secrets.ECR_REGISTRY_URL }}/${{ vars.ECR_REPOSITORY }}
          ecr_image_tag: ${{ needs.build.outputs.image_tag }}
          kube_cert:        ${{ secrets.KUBE_CERT }}
          kube_token:       ${{ secrets.KUBE_TOKEN }}
          kube_cluster:     ${{ secrets.KUBE_CLUSTER }}
          kube_namespace:   ${{ secrets.KUBE_NAMESPACE }}
          app_environment:  staging

  # --------------------------------------------------------- deploy-production ---
  deploy-production:
    name: Deploy (production)
    runs-on: ubuntu-latest
    needs: build
    environment: production
    if: github.ref_name == 'main'
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd

      - name: Deploy to production with composite action
        uses: ./.github/actions/deploy
        with:
          ecr_registry_url: ${{ secrets.ECR_REGISTRY_URL }}/${{ vars.ECR_REPOSITORY }}
          ecr_image_tag: ${{ needs.build.outputs.image_tag }}
          kube_cert:        ${{ secrets.KUBE_CERT }}
          kube_token:       ${{ secrets.KUBE_TOKEN }}
          kube_cluster:     ${{ secrets.KUBE_CLUSTER }}
          kube_namespace:   ${{ secrets.KUBE_NAMESPACE }}
          app_environment:  production