name: Workflow

on:
  pull_request:
  push:
    branches:
      - main
permissions:
  contents: read

jobs:
# -------------------------------------------------- formatting and linting ---
  formatting-and-linting:
    name: "Formatting and linting"
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd
        - uses: ministryofjustice/laa-reusable-github-actions/.github/actions/python-linting-and-formatting@cb1ebcbca5efcd1e91b7ee1e27c73650c1bba9d8

# ------------------------------------------------------------ unit test ------
  unit-tests:
    name: "Unit tests"
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd
        - uses: ./.github/actions/unit-tests

# ------------------------------------------------------------ unit test ------
  integration-tests:
    name: "Integration tests"
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd
        - uses: ./.github/actions/integration-tests

# ---------------------------------------------------------- build (new) -----
  build:
    name: Build Docker Image
    uses: ./.github/workflows/build.yml
    permissions:
      contents: read
      id-token: write
    with:
      ECR_REGION: ${{vars.ECR_REGION}}
      ECR_REPOSITORY: ${{vars.ECR_REPOSITORY}}
    secrets:
      ECR_ROLE_TO_ASSUME: ${{ secrets.ECR_ROLE_TO_ASSUME }}


  snyk-image-scan:
    name: Snyk Image Scan
    needs: build
    if: always() #allowed to be passed for the error
    uses: ministryofjustice/laa-reusable-github-actions/.github/workflows/sast.yml@a652d1076b05dd80d3ab619d263aac6ce526d70b
    permissions:
      id-token: write
      contents: read
      security-events: write
      actions: read
    with:
      image_uri: ${{ needs.build.outputs.image_uri }}
      dockerfile_path: ./Dockerfile
      exclude_base_image_vulns: true
    secrets:
      SNYK_CLIENT_ID: ${{ secrets.SNYK_CLIENT_ID }}
      SNYK_CLIENT_SECRET: ${{ secrets.SNYK_CLIENT_SECRET }}
      ECR_ROLE_TO_ASSUME: ${{ secrets.ECR_ROLE_TO_ASSUME }}


# --------------------------------------------------------- development-production ---
  deploy-development:
    name: Deploy (development)
    runs-on: ubuntu-latest
    needs: build
    environment: development
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd

      - name: Deploy to development with composite action
        uses: ./.github/actions/deploy
        with:
          ecr_registry_url: ${{ secrets.ECR_REGISTRY_URL }}/${{ vars.ECR_REPOSITORY }}
          ecr_image_tag: ${{ needs.build.outputs.image_tag }}
          kube_cert:        ${{ secrets.KUBE_CERT }}
          kube_token:       ${{ secrets.KUBE_TOKEN }}
          kube_cluster:     ${{ secrets.KUBE_CLUSTER }}
          kube_namespace:   ${{ secrets.KUBE_NAMESPACE }}
          app_environment:  development

  # --------------------------------------------------------- staging-production ---
  deploy-staging:
    name: Deploy (staging)
    runs-on: ubuntu-latest
    needs: build
    environment: staging
    if: github.ref_name == 'main'
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd

      - name: Deploy to staging with composite action
        uses: ./.github/actions/deploy
        with:
          ecr_registry_url: ${{ secrets.ECR_REGISTRY_URL }}/${{ vars.ECR_REPOSITORY }}
          ecr_image_tag: ${{ needs.build.outputs.image_tag }}
          kube_cert:        ${{ secrets.KUBE_CERT }}
          kube_token:       ${{ secrets.KUBE_TOKEN }}
          kube_cluster:     ${{ secrets.KUBE_CLUSTER }}
          kube_namespace:   ${{ secrets.KUBE_NAMESPACE }}
          app_environment:  staging

  # --------------------------------------------------------- deploy-production ---
  deploy-production:
    name: Deploy (production)
    runs-on: ubuntu-latest
    needs: build
    environment: production
    if: github.ref_name == 'main'
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd

      - name: Deploy to production with composite action
        uses: ./.github/actions/deploy
        with:
          ecr_registry_url: ${{ secrets.ECR_REGISTRY_URL }}/${{ vars.ECR_REPOSITORY }}
          ecr_image_tag: ${{ needs.build.outputs.image_tag }}
          kube_cert:        ${{ secrets.KUBE_CERT }}
          kube_token:       ${{ secrets.KUBE_TOKEN }}
          kube_cluster:     ${{ secrets.KUBE_CLUSTER }}
          kube_namespace:   ${{ secrets.KUBE_NAMESPACE }}
          app_environment:  production