name: Workflow

on:
  pull_request:

jobs:
  formatting-and-linting:
    name: "Formatting and linting"
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd
        - uses: ./.github/actions/linting-and-formatting
  unit-tests:
    name: "Unit tests"
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd
        - uses: ./.github/actions/unit-tests

  build:
    name: Build Docker Image
    runs-on: ubuntu-latest
    needs: unit-tests
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd

      - name: Set up AWS credentials for ECR and Kubernetes
        uses: aws-actions/configure-aws-credentials@8df5847569e6427dd6c4fb1cf565c83acfa8afa7
        with:
          role-to-assume: ${{ secrets.ECR_ROLE_TO_ASSUME }}
          aws-region: ${{ vars.ECR_REGION }}

      - uses: aws-actions/amazon-ecr-login@062b18b96a7aff071d4dc91bc00c4c1a7945b076
        id: login-ecr

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@e468171a9de216ec08956ac3ada2f0791b6bd435
        with:
          install: true

      - name: Cache Docker layers
        uses: actions/cache@668228422ae6a00e4ad889ee87cd7109ec5666a7
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Set image tag
        id: branch-tag
        run: |
          if [ "${GITHUB_REF_NAME}" = "main" ]; then
            echo "tag=main-${GITHUB_SHA}" >> "$GITHUB_OUTPUT"
          else
            echo "tag=branch-${GITHUB_SHA}" >> "$GITHUB_OUTPUT"
          fi

      - name: Build and push image with local action
        uses: ./.github/actions/build-and-push
        with:
          repo_full_uri:  ${{ secrets.ECR_REGISTRY_URL }}/${{ vars.ECR_REPOSITORY }}
          dockerfile_path: Dockerfile
          image_tag:      ${{ steps.branch-tag.outputs.tag }}

  deploy-development:
    name: Deploy (development)
    runs-on: ubuntu-latest
    needs: build
    environment: development
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd

      - name: Deploy to development with composite action
        uses: ./.github/actions/deploy
        with:
          ecr_registry_url: ${{ secrets.ECR_REGISTRY_URL }}/${{ vars.ECR_REPOSITORY }}
          ecr_image_tag: ${{ steps.branch-tag.outputs.tag }}
          kube_cert:        ${{ secrets.KUBE_CERT }}
          kube_token:       ${{ secrets.KUBE_TOKEN }}
          kube_cluster:     ${{ secrets.KUBE_CLUSTER }}
          kube_namespace:   ${{ secrets.KUBE_NAMESPACE }}
          app_environment:  staging